name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-publish-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build and Publish Python Image
      uses: VaultVulp/gp-docker-action@1.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: python_base
        dockerfile: Dockerfile.python

    - name: Build and Publish Rails Image
      uses: VaultVulp/gp-docker-action@1.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: rails_base
        dockerfile: Dockerfile.rails_app